// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__Syms.h"
#include "Vtop.h"



// FUNCTIONS
Vtop__Syms::Vtop__Syms(Vtop* topp, const char* namep)
    // Setup locals
    : __Vm_namep(namep)
    , __Vm_didInit(false)
    // Setup submodule names
{
    // Pointer to top level
    TOPp = topp;
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOPp->__Vconfigure(this, true);
    // Setup scopes
    __Vscope_KDF_spongent.configure(this, name(), "KDF_spongent", "KDF_spongent", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__counter_impl.configure(this, name(), "KDF_spongent.counter_impl", "counter_impl", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl.configure(this, name(), "KDF_spongent.hash_impl", "hash_impl", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__absorbing_phase_impl.configure(this, name(), "KDF_spongent.hash_impl.absorbing_phase_impl", "absorbing_phase_impl", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__absorbing_phase_impl__counter_impl.configure(this, name(), "KDF_spongent.hash_impl.absorbing_phase_impl.counter_impl", "counter_impl", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__lCounter.configure(this, name(), "KDF_spongent.hash_impl.lCounter", "lCounter", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl", "permutation_impl", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__counter_impl.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.counter_impl", "counter_impl", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__0__KET__.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__0__KET__", "genblk2__BRA\000KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__0__KET____s_box_i.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__0__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__10__KET__.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__10__KET__", "genblk2__BRA__10__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__10__KET____s_box_i.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__10__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__11__KET__.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__11__KET__", "genblk2__BRA__11__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__11__KET____s_box_i.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__11__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__12__KET__.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__12__KET__", "genblk2__BRA__12__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__12__KET____s_box_i.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__12__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__13__KET__.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__13__KET__", "genblk2__BRA__13__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__13__KET____s_box_i.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__13__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__14__KET__.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__14__KET__", "genblk2__BRA__14__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__14__KET____s_box_i.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__14__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__15__KET__.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__15__KET__", "genblk2__BRA__15__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__15__KET____s_box_i.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__15__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__16__KET__.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__16__KET__", "genblk2__BRA__16__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__16__KET____s_box_i.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__16__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__17__KET__.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__17__KET__", "genblk2__BRA__17__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__17__KET____s_box_i.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__17__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__18__KET__.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__18__KET__", "genblk2__BRA__18__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__18__KET____s_box_i.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__18__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__19__KET__.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__19__KET__", "genblk2__BRA__19__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__19__KET____s_box_i.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__19__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__1__KET__.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__1__KET__", "genblk2__BRA__1__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__1__KET____s_box_i.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__1__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__20__KET__.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__20__KET__", "genblk2__BRA__20__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__20__KET____s_box_i.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__20__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__21__KET__.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__21__KET__", "genblk2__BRA__21__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__21__KET____s_box_i.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__21__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__2__KET__.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__2__KET__", "genblk2__BRA__2__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__2__KET____s_box_i.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__2__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__3__KET__.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__3__KET__", "genblk2__BRA__3__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__3__KET____s_box_i.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__3__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__4__KET__.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__4__KET__", "genblk2__BRA__4__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__4__KET____s_box_i.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__4__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__5__KET__.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__5__KET__", "genblk2__BRA__5__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__5__KET____s_box_i.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__5__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__6__KET__.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__6__KET__", "genblk2__BRA__6__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__6__KET____s_box_i.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__6__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__7__KET__.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__7__KET__", "genblk2__BRA__7__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__7__KET____s_box_i.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__7__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__8__KET__.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__8__KET__", "genblk2__BRA__8__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__8__KET____s_box_i.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__8__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__9__KET__.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__9__KET__", "genblk2__BRA__9__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__9__KET____s_box_i.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.genblk2__BRA__9__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__permutation_impl__pLayer_impl.configure(this, name(), "KDF_spongent.hash_impl.permutation_impl.pLayer_impl", "pLayer_impl", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__squeezing_phase_impl.configure(this, name(), "KDF_spongent.hash_impl.squeezing_phase_impl", "squeezing_phase_impl", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__hash_impl__squeezing_phase_impl__counter_impl.configure(this, name(), "KDF_spongent.hash_impl.squeezing_phase_impl.counter_impl", "counter_impl", VerilatedScope::SCOPE_MODULE);
    __Vscope_KDF_spongent__register_data.configure(this, name(), "KDF_spongent.register_data", "register_data", VerilatedScope::SCOPE_MODULE);
    __Vscope_TOP.configure(this, name(), "TOP", "TOP", VerilatedScope::SCOPE_OTHER);
    
    // Setup scope hierarchy
    __Vhier.add(0, &__Vscope_KDF_spongent);
    __Vhier.add(&__Vscope_KDF_spongent, &__Vscope_KDF_spongent__counter_impl);
    __Vhier.add(&__Vscope_KDF_spongent, &__Vscope_KDF_spongent__hash_impl);
    __Vhier.add(&__Vscope_KDF_spongent, &__Vscope_KDF_spongent__register_data);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl, &__Vscope_KDF_spongent__hash_impl__absorbing_phase_impl);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl, &__Vscope_KDF_spongent__hash_impl__lCounter);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl, &__Vscope_KDF_spongent__hash_impl__squeezing_phase_impl);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__absorbing_phase_impl, &__Vscope_KDF_spongent__hash_impl__absorbing_phase_impl__counter_impl);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__permutation_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl__counter_impl);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__permutation_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__0__KET____s_box_i);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__permutation_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__10__KET____s_box_i);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__permutation_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__11__KET____s_box_i);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__permutation_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__12__KET____s_box_i);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__permutation_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__13__KET____s_box_i);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__permutation_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__14__KET____s_box_i);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__permutation_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__15__KET____s_box_i);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__permutation_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__16__KET____s_box_i);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__permutation_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__17__KET____s_box_i);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__permutation_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__18__KET____s_box_i);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__permutation_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__19__KET____s_box_i);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__permutation_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__1__KET____s_box_i);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__permutation_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__20__KET____s_box_i);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__permutation_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__21__KET____s_box_i);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__permutation_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__2__KET____s_box_i);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__permutation_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__3__KET____s_box_i);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__permutation_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__4__KET____s_box_i);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__permutation_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__5__KET____s_box_i);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__permutation_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__6__KET____s_box_i);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__permutation_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__7__KET____s_box_i);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__permutation_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__8__KET____s_box_i);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__permutation_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__9__KET____s_box_i);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__permutation_impl, &__Vscope_KDF_spongent__hash_impl__permutation_impl__pLayer_impl);
    __Vhier.add(&__Vscope_KDF_spongent__hash_impl__squeezing_phase_impl, &__Vscope_KDF_spongent__hash_impl__squeezing_phase_impl__counter_impl);
    
    // Setup export functions
    for (int __Vfinal=0; __Vfinal<2; __Vfinal++) {
        __Vscope_KDF_spongent.varInsert(__Vfinal,"clk", &(TOPp->KDF_spongent__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent.varInsert(__Vfinal,"count", &(TOPp->KDF_spongent__DOT__count), VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_KDF_spongent.varInsert(__Vfinal,"counter_output", &(TOPp->KDF_spongent__DOT__counter_output), VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_KDF_spongent.varInsert(__Vfinal,"counter_up", &(TOPp->KDF_spongent__DOT__counter_up), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent.varInsert(__Vfinal,"end_signal", &(TOPp->KDF_spongent__DOT__end_signal), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent.varInsert(__Vfinal,"hash_end_signal", &(TOPp->KDF_spongent__DOT__hash_end_signal), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent.varInsert(__Vfinal,"hash_input", &(TOPp->KDF_spongent__DOT__hash_input), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,175,0);
        __Vscope_KDF_spongent.varInsert(__Vfinal,"hash_output", &(TOPp->KDF_spongent__DOT__hash_output), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent.varInsert(__Vfinal,"key_derivated", &(TOPp->KDF_spongent__DOT__key_derivated), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent.varInsert(__Vfinal,"register_output", &(TOPp->KDF_spongent__DOT__register_output), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent.varInsert(__Vfinal,"rst", &(TOPp->KDF_spongent__DOT__rst), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent.varInsert(__Vfinal,"rst_hash", &(TOPp->KDF_spongent__DOT__rst_hash), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent.varInsert(__Vfinal,"salt", &(TOPp->KDF_spongent__DOT__salt), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_KDF_spongent.varInsert(__Vfinal,"user_password", &(TOPp->KDF_spongent__DOT__user_password), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,79,0);
        __Vscope_KDF_spongent__counter_impl.varInsert(__Vfinal,"clk", &(TOPp->KDF_spongent__DOT__counter_impl__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__counter_impl.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__counter_impl__DOT__din), VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_KDF_spongent__counter_impl.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__counter_impl__DOT__dout), VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_KDF_spongent__counter_impl.varInsert(__Vfinal,"down", &(TOPp->KDF_spongent__DOT__counter_impl__DOT__down), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__counter_impl.varInsert(__Vfinal,"rst", &(TOPp->KDF_spongent__DOT__counter_impl__DOT__rst), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__counter_impl.varInsert(__Vfinal,"up", &(TOPp->KDF_spongent__DOT__counter_impl__DOT__up), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl.varInsert(__Vfinal,"absorbing_state", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__absorbing_state), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent__hash_impl.varInsert(__Vfinal,"clk", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl.varInsert(__Vfinal,"end_absorbing", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__end_absorbing), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl.varInsert(__Vfinal,"end_hash", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__end_hash), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl.varInsert(__Vfinal,"end_permutation", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__end_permutation), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl.varInsert(__Vfinal,"hash", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__hash), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent__hash_impl.varInsert(__Vfinal,"lCounter_state", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__lCounter_state), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_KDF_spongent__hash_impl.varInsert(__Vfinal,"msg", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__msg), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,175,0);
        __Vscope_KDF_spongent__hash_impl.varInsert(__Vfinal,"padded_msg", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__padded_msg), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,183,0);
        __Vscope_KDF_spongent__hash_impl.varInsert(__Vfinal,"permutation_initial_state", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_initial_state), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent__hash_impl.varInsert(__Vfinal,"permutation_initial_state_from_absorb", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_initial_state_from_absorb), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent__hash_impl.varInsert(__Vfinal,"permutation_initial_state_from_squezzing", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_initial_state_from_squezzing), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent__hash_impl.varInsert(__Vfinal,"permutation_state", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_state), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent__hash_impl.varInsert(__Vfinal,"rst", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__rst), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl.varInsert(__Vfinal,"rst_lCounter", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__rst_lCounter), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl.varInsert(__Vfinal,"rst_permutation", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__rst_permutation), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl.varInsert(__Vfinal,"rst_permutation_from_absorb", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__rst_permutation_from_absorb), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl.varInsert(__Vfinal,"rst_permutation_from_squezzing", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__rst_permutation_from_squezzing), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl.varInsert(__Vfinal,"shift_lCounter", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__shift_lCounter), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__absorbing_phase_impl.varInsert(__Vfinal,"absorbing_state", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__absorbing_phase_impl__DOT__absorbing_state), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent__hash_impl__absorbing_phase_impl.varInsert(__Vfinal,"clk", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__absorbing_phase_impl__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__absorbing_phase_impl.varInsert(__Vfinal,"counter_o", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__absorbing_phase_impl__DOT__counter_o), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_KDF_spongent__hash_impl__absorbing_phase_impl.varInsert(__Vfinal,"counter_up", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__absorbing_phase_impl__DOT__counter_up), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__absorbing_phase_impl.varInsert(__Vfinal,"current_state", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__absorbing_phase_impl__DOT__current_state), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_KDF_spongent__hash_impl__absorbing_phase_impl.varInsert(__Vfinal,"end_absorbing", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__absorbing_phase_impl__DOT__end_absorbing), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__absorbing_phase_impl.varInsert(__Vfinal,"end_permutation", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__absorbing_phase_impl__DOT__end_permutation), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__absorbing_phase_impl.varInsert(__Vfinal,"msg_chunk", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__absorbing_phase_impl__DOT__msg_chunk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_KDF_spongent__hash_impl__absorbing_phase_impl.varInsert(__Vfinal,"next_state", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__absorbing_phase_impl__DOT__next_state), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_KDF_spongent__hash_impl__absorbing_phase_impl.varInsert(__Vfinal,"padded_msg", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__absorbing_phase_impl__DOT__padded_msg), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,183,0);
        __Vscope_KDF_spongent__hash_impl__absorbing_phase_impl.varInsert(__Vfinal,"permutation_initial_state", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__absorbing_phase_impl__DOT__permutation_initial_state), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent__hash_impl__absorbing_phase_impl.varInsert(__Vfinal,"permutation_state", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__absorbing_phase_impl__DOT__permutation_state), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent__hash_impl__absorbing_phase_impl.varInsert(__Vfinal,"rst", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__absorbing_phase_impl__DOT__rst), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__absorbing_phase_impl.varInsert(__Vfinal,"rst_permutation", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__absorbing_phase_impl__DOT__rst_permutation), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__absorbing_phase_impl.varInsert(__Vfinal,"state", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__absorbing_phase_impl__DOT__state), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent__hash_impl__absorbing_phase_impl__counter_impl.varInsert(__Vfinal,"clk", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__absorbing_phase_impl__DOT__counter_impl__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__absorbing_phase_impl__counter_impl.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__absorbing_phase_impl__DOT__counter_impl__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_KDF_spongent__hash_impl__absorbing_phase_impl__counter_impl.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__absorbing_phase_impl__DOT__counter_impl__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_KDF_spongent__hash_impl__absorbing_phase_impl__counter_impl.varInsert(__Vfinal,"down", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__absorbing_phase_impl__DOT__counter_impl__DOT__down), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__absorbing_phase_impl__counter_impl.varInsert(__Vfinal,"rst", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__absorbing_phase_impl__DOT__counter_impl__DOT__rst), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__absorbing_phase_impl__counter_impl.varInsert(__Vfinal,"up", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__absorbing_phase_impl__DOT__counter_impl__DOT__up), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__lCounter.varInsert(__Vfinal,"bit_xored", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__lCounter__DOT__bit_xored), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__lCounter.varInsert(__Vfinal,"clk", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__lCounter__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__lCounter.varInsert(__Vfinal,"feedback_coeff", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__lCounter__DOT__feedback_coeff), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_KDF_spongent__hash_impl__lCounter.varInsert(__Vfinal,"initial_state", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__lCounter__DOT__initial_state), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_KDF_spongent__hash_impl__lCounter.varInsert(__Vfinal,"rst", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__lCounter__DOT__rst), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__lCounter.varInsert(__Vfinal,"shift", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__lCounter__DOT__shift), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__lCounter.varInsert(__Vfinal,"state", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__lCounter__DOT__state), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_KDF_spongent__hash_impl__lCounter.varInsert(__Vfinal,"state_reg", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__lCounter__DOT__state_reg), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl.varInsert(__Vfinal,"clk", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl.varInsert(__Vfinal,"counter_o", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__counter_o), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl.varInsert(__Vfinal,"end_permutation", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__end_permutation), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl.varInsert(__Vfinal,"initial_state", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__initial_state), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl.varInsert(__Vfinal,"lCounter_state", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__lCounter_state), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl.varInsert(__Vfinal,"reverse_lCounter", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__reverse_lCounter), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl.varInsert(__Vfinal,"rst", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__rst), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl.varInsert(__Vfinal,"rst_lCounter", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__rst_lCounter), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl.varInsert(__Vfinal,"shift_lCounter", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__shift_lCounter), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl.varInsert(__Vfinal,"state", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__state), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl.varInsert(__Vfinal,"state_S_box", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__state_S_box), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl.varInsert(__Vfinal,"state_reg", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__state_reg), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__counter_impl.varInsert(__Vfinal,"clk", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__counter_impl__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__counter_impl.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__counter_impl__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__counter_impl.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__counter_impl__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__counter_impl.varInsert(__Vfinal,"down", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__counter_impl__DOT__down), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__counter_impl.varInsert(__Vfinal,"rst", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__counter_impl__DOT__rst), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__counter_impl.varInsert(__Vfinal,"up", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__counter_impl__DOT__up), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__0__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__0__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__0__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__0__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__10__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__10__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__10__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__10__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__11__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__11__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__11__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__11__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__12__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__12__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__12__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__12__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__13__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__13__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__13__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__13__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__14__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__14__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__14__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__14__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__15__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__15__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__15__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__15__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__16__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__16__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__16__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__16__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__17__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__17__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__17__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__17__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__18__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__18__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__18__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__18__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__19__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__19__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__19__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__19__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__1__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__1__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__1__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__1__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__20__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__20__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__20__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__20__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__21__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__21__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__21__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__21__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__2__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__2__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__2__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__2__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__3__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__3__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__3__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__3__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__4__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__4__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__4__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__4__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__5__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__5__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__5__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__5__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__6__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__6__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__6__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__6__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__7__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__7__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__7__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__7__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__8__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__8__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__8__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__8__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__9__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__9__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__genblk2__BRA__9__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__genblk2__BRA__9__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__pLayer_impl.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__pLayer_impl__DOT__din), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent__hash_impl__permutation_impl__pLayer_impl.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__permutation_impl__DOT__pLayer_impl__DOT__dout), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent__hash_impl__squeezing_phase_impl.varInsert(__Vfinal,"clk", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__squeezing_phase_impl__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__squeezing_phase_impl.varInsert(__Vfinal,"counter_o", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__squeezing_phase_impl__DOT__counter_o), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_KDF_spongent__hash_impl__squeezing_phase_impl.varInsert(__Vfinal,"counter_up", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__squeezing_phase_impl__DOT__counter_up), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__squeezing_phase_impl.varInsert(__Vfinal,"current_state", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__squeezing_phase_impl__DOT__current_state), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_KDF_spongent__hash_impl__squeezing_phase_impl.varInsert(__Vfinal,"end_permutation", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__squeezing_phase_impl__DOT__end_permutation), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__squeezing_phase_impl.varInsert(__Vfinal,"end_squeezing", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__squeezing_phase_impl__DOT__end_squeezing), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__squeezing_phase_impl.varInsert(__Vfinal,"next_state", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__squeezing_phase_impl__DOT__next_state), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_KDF_spongent__hash_impl__squeezing_phase_impl.varInsert(__Vfinal,"permutation_initial_state", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__squeezing_phase_impl__DOT__permutation_initial_state), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent__hash_impl__squeezing_phase_impl.varInsert(__Vfinal,"permutation_state", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__squeezing_phase_impl__DOT__permutation_state), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent__hash_impl__squeezing_phase_impl.varInsert(__Vfinal,"result", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__squeezing_phase_impl__DOT__result), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent__hash_impl__squeezing_phase_impl.varInsert(__Vfinal,"result_chunk", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__squeezing_phase_impl__DOT__result_chunk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_KDF_spongent__hash_impl__squeezing_phase_impl.varInsert(__Vfinal,"rst", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__squeezing_phase_impl__DOT__rst), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__squeezing_phase_impl.varInsert(__Vfinal,"rst_permutation", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__squeezing_phase_impl__DOT__rst_permutation), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__squeezing_phase_impl.varInsert(__Vfinal,"state", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__squeezing_phase_impl__DOT__state), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent__hash_impl__squeezing_phase_impl__counter_impl.varInsert(__Vfinal,"clk", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__squeezing_phase_impl__DOT__counter_impl__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__squeezing_phase_impl__counter_impl.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__squeezing_phase_impl__DOT__counter_impl__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_KDF_spongent__hash_impl__squeezing_phase_impl__counter_impl.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__squeezing_phase_impl__DOT__counter_impl__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_KDF_spongent__hash_impl__squeezing_phase_impl__counter_impl.varInsert(__Vfinal,"down", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__squeezing_phase_impl__DOT__counter_impl__DOT__down), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__squeezing_phase_impl__counter_impl.varInsert(__Vfinal,"rst", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__squeezing_phase_impl__DOT__counter_impl__DOT__rst), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__hash_impl__squeezing_phase_impl__counter_impl.varInsert(__Vfinal,"up", &(TOPp->KDF_spongent__DOT__hash_impl__DOT__squeezing_phase_impl__DOT__counter_impl__DOT__up), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__register_data.varInsert(__Vfinal,"cl", &(TOPp->KDF_spongent__DOT__register_data__DOT__cl), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__register_data.varInsert(__Vfinal,"clk", &(TOPp->KDF_spongent__DOT__register_data__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_KDF_spongent__register_data.varInsert(__Vfinal,"din", &(TOPp->KDF_spongent__DOT__register_data__DOT__din), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent__register_data.varInsert(__Vfinal,"dout", &(TOPp->KDF_spongent__DOT__register_data__DOT__dout), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,87,0);
        __Vscope_KDF_spongent__register_data.varInsert(__Vfinal,"w", &(TOPp->KDF_spongent__DOT__register_data__DOT__w), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"clk", &(TOPp->clk), VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"count", &(TOPp->count), VLVT_UINT32,VLVD_IN|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"end_signal", &(TOPp->end_signal), VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"key_derivated", &(TOPp->key_derivated), VLVT_WDATA,VLVD_OUT|VLVF_PUB_RW,1 ,87,0);
        __Vscope_TOP.varInsert(__Vfinal,"rst", &(TOPp->rst), VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"salt", &(TOPp->salt), VLVT_UINT64,VLVD_IN|VLVF_PUB_RW,1 ,63,0);
        __Vscope_TOP.varInsert(__Vfinal,"user_password", &(TOPp->user_password), VLVT_WDATA,VLVD_IN|VLVF_PUB_RW,1 ,79,0);
    }
}
