FROM debian:bookworm

WORKDIR /core

ARG PYTHON_VERSION=3.11

ARG COCOTB_VERSION=1.9.2

ARG NUMPY_VERSION=2.2.3

ARG BITSTRING_VERSION=4.3.0

ARG FUSESOC_VERSION=2.4.2

ARG VERILATOR_VERSION=5.032

RUN apt-get update

RUN apt-get install -y python${PYTHON_VERSION} python3 python3-venv python${PYTHON_VERSION}-venv build-essential python3-dev iverilog git flex bison help2man perl make autoconf

RUN python3.11 -m venv /core/venv

RUN . venv/bin/activate && pip install cocotb==${COCOTB_VERSION} bitstring==${BITSTRING_VERSION} fusesoc==${FUSESOC_VERSION} numpy==${NUMPY_VERSION} pytest

RUN . venv/bin/activate && fusesoc library add fusesoc_cores https://github.com/germancq/IPCores

RUN git clone https://github.com/germancq/IPCores.git

RUN git clone https://github.com/verilator/verilator

RUN unset VERILATOR_ROOT

RUN cd verilator && git checkout v${VERILATOR_VERSION} && autoconf && ./configure && make && make install

RUN echo 'export PATH="/usr/local:$PATH"' >> /root/.bashrc

CMD [ "bash" ]
