# @Author: German Cano Quiveu <germancq>
# @Date:   2018-11-15T13:52:40+01:00
# @Email:  germancq@dte.us.es
# @Filename: Makefile
# @Last modified by:   germancq
# @Last modified time: 2018-11-15T13:53:13+01:00


VERILOG_SOURCES = ../../hdl_code/sdcmd.sv \
				  ../../../misc/counters/hdl_code/counter.sv \
				  ../../../misc/registers/hdl_code/register.sv 
TOPLEVEL=sdcmd
MODULE=sdcmd_test
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
