// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef _Vtop_adder_H_
#define _Vtop_adder_H_

#include "verilated.h"
#include "Vtop__Dpi.h"

class Vtop__Syms;

//----------

VL_MODULE(Vtop_adder) {
  public:
    
    // PORTS
    VL_OUT8(c,0,0);
    VL_IN(a,31,0);
    VL_IN(b,31,0);
    VL_OUT(s,31,0);
    
    // LOCAL SIGNALS
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ h0__DOT__a;
        CData/*0:0*/ h0__DOT__b;
        CData/*0:0*/ h0__DOT__carry;
        CData/*0:0*/ h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__1__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__1__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__1__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__1__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__1__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__1__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__1__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__1__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__1__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__1__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__1__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__1__KET____DOT__f_i__DOT__h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__1__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__1__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__1__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__1__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__2__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__2__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__2__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__2__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__2__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__2__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__2__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__2__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__2__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__2__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__2__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__2__KET____DOT__f_i__DOT__h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__2__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__2__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__2__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__2__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__3__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__3__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__3__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__3__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__3__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__3__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__3__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__3__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__3__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__3__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__3__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__3__KET____DOT__f_i__DOT__h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__3__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__3__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__3__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__3__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__4__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__4__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__4__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__4__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__4__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__4__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__4__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__4__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__4__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__4__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__4__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__4__KET____DOT__f_i__DOT__h0__DOT__s;
    };
    struct {
        CData/*0:0*/ genblk1__BRA__4__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__4__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__4__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__4__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__5__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__5__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__5__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__5__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__5__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__5__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__5__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__5__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__5__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__5__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__5__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__5__KET____DOT__f_i__DOT__h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__5__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__5__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__5__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__5__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__6__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__6__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__6__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__6__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__6__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__6__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__6__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__6__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__6__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__6__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__6__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__6__KET____DOT__f_i__DOT__h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__6__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__6__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__6__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__6__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__7__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__7__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__7__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__7__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__7__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__7__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__7__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__7__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__7__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__7__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__7__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__7__KET____DOT__f_i__DOT__h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__7__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__7__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__7__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__7__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__8__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__8__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__8__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__8__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__8__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__8__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__8__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__8__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__8__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__8__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__8__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__8__KET____DOT__f_i__DOT__h0__DOT__s;
    };
    struct {
        CData/*0:0*/ genblk1__BRA__8__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__8__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__8__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__8__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__9__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__9__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__9__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__9__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__9__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__9__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__9__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__9__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__9__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__9__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__9__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__9__KET____DOT__f_i__DOT__h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__9__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__9__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__9__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__9__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__10__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__10__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__10__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__10__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__10__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__10__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__10__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__10__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__10__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__10__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__10__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__10__KET____DOT__f_i__DOT__h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__10__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__10__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__10__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__10__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__11__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__11__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__11__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__11__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__11__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__11__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__11__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__11__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__11__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__11__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__11__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__11__KET____DOT__f_i__DOT__h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__11__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__11__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__11__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__11__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__12__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__12__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__12__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__12__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__12__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__12__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__12__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__12__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__12__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__12__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__12__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__12__KET____DOT__f_i__DOT__h0__DOT__s;
    };
    struct {
        CData/*0:0*/ genblk1__BRA__12__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__12__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__12__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__12__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__13__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__13__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__13__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__13__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__13__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__13__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__13__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__13__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__13__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__13__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__13__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__13__KET____DOT__f_i__DOT__h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__13__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__13__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__13__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__13__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__14__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__14__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__14__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__14__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__14__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__14__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__14__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__14__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__14__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__14__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__14__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__14__KET____DOT__f_i__DOT__h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__14__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__14__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__14__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__14__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__15__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__15__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__15__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__15__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__15__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__15__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__15__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__15__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__15__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__15__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__15__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__15__KET____DOT__f_i__DOT__h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__15__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__15__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__15__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__15__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__16__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__16__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__16__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__16__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__16__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__16__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__16__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__16__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__16__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__16__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__16__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__16__KET____DOT__f_i__DOT__h0__DOT__s;
    };
    struct {
        CData/*0:0*/ genblk1__BRA__16__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__16__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__16__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__16__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__17__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__17__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__17__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__17__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__17__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__17__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__17__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__17__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__17__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__17__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__17__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__17__KET____DOT__f_i__DOT__h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__17__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__17__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__17__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__17__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__18__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__18__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__18__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__18__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__18__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__18__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__18__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__18__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__18__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__18__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__18__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__18__KET____DOT__f_i__DOT__h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__18__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__18__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__18__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__18__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__19__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__19__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__19__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__19__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__19__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__19__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__19__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__19__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__19__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__19__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__19__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__19__KET____DOT__f_i__DOT__h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__19__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__19__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__19__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__19__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__20__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__20__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__20__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__20__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__20__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__20__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__20__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__20__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__20__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__20__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__20__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__20__KET____DOT__f_i__DOT__h0__DOT__s;
    };
    struct {
        CData/*0:0*/ genblk1__BRA__20__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__20__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__20__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__20__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__21__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__21__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__21__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__21__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__21__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__21__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__21__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__21__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__21__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__21__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__21__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__21__KET____DOT__f_i__DOT__h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__21__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__21__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__21__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__21__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__22__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__22__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__22__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__22__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__22__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__22__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__22__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__22__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__22__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__22__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__22__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__22__KET____DOT__f_i__DOT__h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__22__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__22__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__22__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__22__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__23__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__23__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__23__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__23__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__23__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__23__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__23__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__23__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__23__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__23__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__23__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__23__KET____DOT__f_i__DOT__h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__23__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__23__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__23__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__23__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__24__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__24__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__24__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__24__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__24__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__24__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__24__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__24__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__24__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__24__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__24__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__24__KET____DOT__f_i__DOT__h0__DOT__s;
    };
    struct {
        CData/*0:0*/ genblk1__BRA__24__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__24__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__24__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__24__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__25__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__25__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__25__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__25__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__25__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__25__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__25__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__25__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__25__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__25__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__25__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__25__KET____DOT__f_i__DOT__h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__25__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__25__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__25__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__25__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__26__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__26__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__26__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__26__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__26__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__26__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__26__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__26__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__26__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__26__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__26__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__26__KET____DOT__f_i__DOT__h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__26__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__26__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__26__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__26__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__27__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__27__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__27__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__27__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__27__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__27__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__27__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__27__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__27__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__27__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__27__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__27__KET____DOT__f_i__DOT__h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__27__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__27__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__27__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__27__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__28__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__28__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__28__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__28__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__28__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__28__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__28__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__28__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__28__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__28__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__28__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__28__KET____DOT__f_i__DOT__h0__DOT__s;
    };
    struct {
        CData/*0:0*/ genblk1__BRA__28__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__28__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__28__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__28__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__29__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__29__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__29__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__29__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__29__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__29__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__29__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__29__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__29__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__29__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__29__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__29__KET____DOT__f_i__DOT__h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__29__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__29__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__29__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__29__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__30__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__30__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__30__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__30__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__30__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__30__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__30__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__30__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__30__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__30__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__30__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__30__KET____DOT__f_i__DOT__h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__30__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__30__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__30__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__30__KET____DOT__f_i__DOT__h1__DOT__s;
        CData/*0:0*/ genblk1__BRA__31__KET____DOT__f_i__DOT__a;
        CData/*0:0*/ genblk1__BRA__31__KET____DOT__f_i__DOT__b;
        CData/*0:0*/ genblk1__BRA__31__KET____DOT__f_i__DOT__c;
        CData/*0:0*/ genblk1__BRA__31__KET____DOT__f_i__DOT__carry;
        CData/*0:0*/ genblk1__BRA__31__KET____DOT__f_i__DOT__s;
        CData/*0:0*/ genblk1__BRA__31__KET____DOT__f_i__DOT__c_0;
        CData/*0:0*/ genblk1__BRA__31__KET____DOT__f_i__DOT__c_1;
        CData/*0:0*/ genblk1__BRA__31__KET____DOT__f_i__DOT__s_0;
        CData/*0:0*/ genblk1__BRA__31__KET____DOT__f_i__DOT__h0__DOT__a;
        CData/*0:0*/ genblk1__BRA__31__KET____DOT__f_i__DOT__h0__DOT__b;
        CData/*0:0*/ genblk1__BRA__31__KET____DOT__f_i__DOT__h0__DOT__carry;
        CData/*0:0*/ genblk1__BRA__31__KET____DOT__f_i__DOT__h0__DOT__s;
        CData/*0:0*/ genblk1__BRA__31__KET____DOT__f_i__DOT__h1__DOT__a;
        CData/*0:0*/ genblk1__BRA__31__KET____DOT__f_i__DOT__h1__DOT__b;
        CData/*0:0*/ genblk1__BRA__31__KET____DOT__f_i__DOT__h1__DOT__carry;
        CData/*0:0*/ genblk1__BRA__31__KET____DOT__f_i__DOT__h1__DOT__s;
        IData/*31:0*/ carry_values;
    };
    
    // LOCAL VARIABLES
    
    // INTERNAL VARIABLES
  private:
    Vtop__Syms* __VlSymsp;  // Symbol table
  public:
    
    // PARAMETERS
    
    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(Vtop_adder);  ///< Copying not allowed
  public:
    Vtop_adder(const char* name = "TOP");
    ~Vtop_adder();
    
    // API METHODS
    
    // INTERNAL METHODS
    void __Vconfigure(Vtop__Syms* symsp, bool first);
    void _combo__TOP__twofish_ctr__DOT__genblk1__BRA__0__KET____DOT__key_words_i__DOT__ai__33(Vtop__Syms* __restrict vlSymsp);
    void _combo__TOP__twofish_ctr__DOT__stage_impl__DOT__f_i__DOT__at01__59(Vtop__Syms* __restrict vlSymsp);
    void _combo__TOP__twofish_ctr__DOT__stage_impl__DOT__f_i__DOT__at01__62(Vtop__Syms* __restrict vlSymsp);
  private:
    void _ctor_var_reset() VL_ATTR_COLD;
  public:
    void _settle__TOP__twofish_ctr__DOT__stage_impl__DOT__f_i__DOT__at00__27(Vtop__Syms* __restrict vlSymsp);
    void _settle__TOP__twofish_ctr__DOT__stage_impl__DOT__f_i__DOT__at01__28(Vtop__Syms* __restrict vlSymsp);
    void _settle__TOP__twofish_ctr__DOT__stage_impl__DOT__f_i__DOT__at01__31(Vtop__Syms* __restrict vlSymsp);
    void _settle__TOP__twofish_ctr__DOT__stage_impl__DOT__f_i__DOT__k_0__DOT__ai__5(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
} VL_ATTR_ALIGNED(128);

#endif // guard
