// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table internal header
//
// Internal details; most calling programs do not need this header,
// unless using verilator public meta comments.

#ifndef _Vtop__Syms_H_
#define _Vtop__Syms_H_

#include "verilated.h"

// INCLUDE MODULE CLASSES
#include "Vtop.h"

// DPI TYPES for DPI Export callbacks (Internal use)

// SYMS CLASS
class Vtop__Syms : public VerilatedSyms {
  public:
    
    // LOCAL STATE
    const char* __Vm_namep;
    bool __Vm_didInit;
    
    // SUBCELL STATE
    Vtop*                          TOPp;
    
    // SCOPE NAMES
    VerilatedScope __Vscope_TOP;
    VerilatedScope __Vscope_present;
    VerilatedScope __Vscope_present__key_sch_impl;
    VerilatedScope __Vscope_present__key_sch_impl__counter_impl;
    VerilatedScope __Vscope_present__key_sch_impl__key_register;
    VerilatedScope __Vscope_present__key_sch_impl__memory_impl;
    VerilatedScope __Vscope_present__key_sch_impl__sbox;
    VerilatedScope __Vscope_present__present_dec_impl;
    VerilatedScope __Vscope_present__present_dec_impl__block_register;
    VerilatedScope __Vscope_present__present_dec_impl__counter_impl;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__player_i;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__0__KET__;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__0__KET____sbox;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__10__KET__;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__10__KET____sbox;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__11__KET__;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__11__KET____sbox;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__12__KET__;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__12__KET____sbox;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__13__KET__;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__13__KET____sbox;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__14__KET__;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__14__KET____sbox;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__15__KET__;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__15__KET____sbox;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__1__KET__;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__1__KET____sbox;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__2__KET__;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__2__KET____sbox;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__3__KET__;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__3__KET____sbox;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__4__KET__;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__4__KET____sbox;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__5__KET__;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__5__KET____sbox;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__6__KET__;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__6__KET____sbox;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__7__KET__;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__7__KET____sbox;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__8__KET__;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__8__KET____sbox;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__9__KET__;
    VerilatedScope __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__9__KET____sbox;
    VerilatedScope __Vscope_present__present_enc_impl;
    VerilatedScope __Vscope_present__present_enc_impl__block_register;
    VerilatedScope __Vscope_present__present_enc_impl__counter_impl;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__player_i;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__0__KET__;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__0__KET____sbox;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__10__KET__;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__10__KET____sbox;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__11__KET__;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__11__KET____sbox;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__12__KET__;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__12__KET____sbox;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__13__KET__;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__13__KET____sbox;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__14__KET__;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__14__KET____sbox;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__15__KET__;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__15__KET____sbox;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__1__KET__;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__1__KET____sbox;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__2__KET__;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__2__KET____sbox;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__3__KET__;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__3__KET____sbox;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__4__KET__;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__4__KET____sbox;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__5__KET__;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__5__KET____sbox;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__6__KET__;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__6__KET____sbox;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__7__KET__;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__7__KET____sbox;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__8__KET__;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__8__KET____sbox;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__9__KET__;
    VerilatedScope __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__9__KET____sbox;
    VerilatedScope __Vscope_present__reg_end_signal;
    VerilatedScope __Vscope_present__result;
    
    // SCOPE HIERARCHY
    VerilatedHierarchy __Vhier;
    
    // CREATORS
    Vtop__Syms(Vtop* topp, const char* namep);
    ~Vtop__Syms() {}
    
    // METHODS
    inline const char* name() { return __Vm_namep; }
    
} VL_ATTR_ALIGNED(64);

#endif  // guard
