// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__Syms.h"
#include "Vtop.h"



// FUNCTIONS
Vtop__Syms::Vtop__Syms(Vtop* topp, const char* namep)
    // Setup locals
    : __Vm_namep(namep)
    , __Vm_didInit(false)
    // Setup submodule names
{
    // Pointer to top level
    TOPp = topp;
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOPp->__Vconfigure(this, true);
    // Setup scopes
    __Vscope_TOP.configure(this, name(), "TOP", "TOP", VerilatedScope::SCOPE_OTHER);
    __Vscope_present.configure(this, name(), "present", "present", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__key_sch_impl.configure(this, name(), "present.key_sch_impl", "key_sch_impl", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__key_sch_impl__counter_impl.configure(this, name(), "present.key_sch_impl.counter_impl", "counter_impl", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__key_sch_impl__key_register.configure(this, name(), "present.key_sch_impl.key_register", "key_register", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__key_sch_impl__memory_impl.configure(this, name(), "present.key_sch_impl.memory_impl", "memory_impl", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__key_sch_impl__sbox.configure(this, name(), "present.key_sch_impl.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_dec_impl.configure(this, name(), "present.present_dec_impl", "present_dec_impl", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_dec_impl__block_register.configure(this, name(), "present.present_dec_impl.block_register", "block_register", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_dec_impl__counter_impl.configure(this, name(), "present.present_dec_impl.counter_impl", "counter_impl", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_dec_impl__dec_stage_impl.configure(this, name(), "present.present_dec_impl.dec_stage_impl", "dec_stage_impl", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_dec_impl__dec_stage_impl__player_i.configure(this, name(), "present.present_dec_impl.dec_stage_impl.player_i", "player_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i", "slayer_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__0__KET__.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__0__KET__", "genblk1__BRA\000KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__0__KET____sbox.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__0__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__10__KET__.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__10__KET__", "genblk1__BRA__10__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__10__KET____sbox.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__10__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__11__KET__.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__11__KET__", "genblk1__BRA__11__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__11__KET____sbox.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__11__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__12__KET__.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__12__KET__", "genblk1__BRA__12__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__12__KET____sbox.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__12__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__13__KET__.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__13__KET__", "genblk1__BRA__13__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__13__KET____sbox.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__13__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__14__KET__.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__14__KET__", "genblk1__BRA__14__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__14__KET____sbox.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__14__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__15__KET__.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__15__KET__", "genblk1__BRA__15__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__15__KET____sbox.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__15__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__1__KET__.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__1__KET__", "genblk1__BRA__1__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__1__KET____sbox.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__1__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__2__KET__.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__2__KET__", "genblk1__BRA__2__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__2__KET____sbox.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__2__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__3__KET__.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__3__KET__", "genblk1__BRA__3__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__3__KET____sbox.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__3__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__4__KET__.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__4__KET__", "genblk1__BRA__4__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__4__KET____sbox.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__4__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__5__KET__.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__5__KET__", "genblk1__BRA__5__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__5__KET____sbox.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__5__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__6__KET__.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__6__KET__", "genblk1__BRA__6__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__6__KET____sbox.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__6__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__7__KET__.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__7__KET__", "genblk1__BRA__7__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__7__KET____sbox.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__7__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__8__KET__.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__8__KET__", "genblk1__BRA__8__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__8__KET____sbox.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__8__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__9__KET__.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__9__KET__", "genblk1__BRA__9__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__9__KET____sbox.configure(this, name(), "present.present_dec_impl.dec_stage_impl.slayer_i.genblk1__BRA__9__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_enc_impl.configure(this, name(), "present.present_enc_impl", "present_enc_impl", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_enc_impl__block_register.configure(this, name(), "present.present_enc_impl.block_register", "block_register", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_enc_impl__counter_impl.configure(this, name(), "present.present_enc_impl.counter_impl", "counter_impl", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_enc_impl__enc_stage_impl.configure(this, name(), "present.present_enc_impl.enc_stage_impl", "enc_stage_impl", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_enc_impl__enc_stage_impl__player_i.configure(this, name(), "present.present_enc_impl.enc_stage_impl.player_i", "player_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i", "slayer_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__0__KET__.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__0__KET__", "genblk1__BRA\000KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__0__KET____sbox.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__0__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__10__KET__.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__10__KET__", "genblk1__BRA__10__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__10__KET____sbox.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__10__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__11__KET__.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__11__KET__", "genblk1__BRA__11__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__11__KET____sbox.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__11__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__12__KET__.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__12__KET__", "genblk1__BRA__12__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__12__KET____sbox.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__12__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__13__KET__.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__13__KET__", "genblk1__BRA__13__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__13__KET____sbox.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__13__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__14__KET__.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__14__KET__", "genblk1__BRA__14__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__14__KET____sbox.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__14__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__15__KET__.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__15__KET__", "genblk1__BRA__15__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__15__KET____sbox.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__15__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__1__KET__.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__1__KET__", "genblk1__BRA__1__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__1__KET____sbox.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__1__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__2__KET__.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__2__KET__", "genblk1__BRA__2__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__2__KET____sbox.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__2__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__3__KET__.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__3__KET__", "genblk1__BRA__3__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__3__KET____sbox.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__3__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__4__KET__.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__4__KET__", "genblk1__BRA__4__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__4__KET____sbox.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__4__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__5__KET__.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__5__KET__", "genblk1__BRA__5__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__5__KET____sbox.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__5__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__6__KET__.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__6__KET__", "genblk1__BRA__6__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__6__KET____sbox.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__6__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__7__KET__.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__7__KET__", "genblk1__BRA__7__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__7__KET____sbox.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__7__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__8__KET__.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__8__KET__", "genblk1__BRA__8__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__8__KET____sbox.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__8__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__9__KET__.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__9__KET__", "genblk1__BRA__9__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__9__KET____sbox.configure(this, name(), "present.present_enc_impl.enc_stage_impl.slayer_i.genblk1__BRA__9__KET__.sbox", "sbox", VerilatedScope::SCOPE_MODULE);
    __Vscope_present__result.configure(this, name(), "present.result", "result", VerilatedScope::SCOPE_MODULE);
    
    // Setup scope hierarchy
    __Vhier.add(0, &__Vscope_present);
    __Vhier.add(&__Vscope_present, &__Vscope_present__key_sch_impl);
    __Vhier.add(&__Vscope_present, &__Vscope_present__present_dec_impl);
    __Vhier.add(&__Vscope_present, &__Vscope_present__present_enc_impl);
    __Vhier.add(&__Vscope_present, &__Vscope_present__result);
    __Vhier.add(&__Vscope_present__key_sch_impl, &__Vscope_present__key_sch_impl__counter_impl);
    __Vhier.add(&__Vscope_present__key_sch_impl, &__Vscope_present__key_sch_impl__key_register);
    __Vhier.add(&__Vscope_present__key_sch_impl, &__Vscope_present__key_sch_impl__memory_impl);
    __Vhier.add(&__Vscope_present__key_sch_impl, &__Vscope_present__key_sch_impl__sbox);
    __Vhier.add(&__Vscope_present__present_dec_impl, &__Vscope_present__present_dec_impl__block_register);
    __Vhier.add(&__Vscope_present__present_dec_impl, &__Vscope_present__present_dec_impl__counter_impl);
    __Vhier.add(&__Vscope_present__present_dec_impl, &__Vscope_present__present_dec_impl__dec_stage_impl);
    __Vhier.add(&__Vscope_present__present_dec_impl__dec_stage_impl, &__Vscope_present__present_dec_impl__dec_stage_impl__player_i);
    __Vhier.add(&__Vscope_present__present_dec_impl__dec_stage_impl, &__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i);
    __Vhier.add(&__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i, &__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__0__KET____sbox);
    __Vhier.add(&__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i, &__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__10__KET____sbox);
    __Vhier.add(&__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i, &__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__11__KET____sbox);
    __Vhier.add(&__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i, &__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__12__KET____sbox);
    __Vhier.add(&__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i, &__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__13__KET____sbox);
    __Vhier.add(&__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i, &__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__14__KET____sbox);
    __Vhier.add(&__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i, &__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__15__KET____sbox);
    __Vhier.add(&__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i, &__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__1__KET____sbox);
    __Vhier.add(&__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i, &__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__2__KET____sbox);
    __Vhier.add(&__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i, &__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__3__KET____sbox);
    __Vhier.add(&__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i, &__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__4__KET____sbox);
    __Vhier.add(&__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i, &__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__5__KET____sbox);
    __Vhier.add(&__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i, &__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__6__KET____sbox);
    __Vhier.add(&__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i, &__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__7__KET____sbox);
    __Vhier.add(&__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i, &__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__8__KET____sbox);
    __Vhier.add(&__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i, &__Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__9__KET____sbox);
    __Vhier.add(&__Vscope_present__present_enc_impl, &__Vscope_present__present_enc_impl__block_register);
    __Vhier.add(&__Vscope_present__present_enc_impl, &__Vscope_present__present_enc_impl__counter_impl);
    __Vhier.add(&__Vscope_present__present_enc_impl, &__Vscope_present__present_enc_impl__enc_stage_impl);
    __Vhier.add(&__Vscope_present__present_enc_impl__enc_stage_impl, &__Vscope_present__present_enc_impl__enc_stage_impl__player_i);
    __Vhier.add(&__Vscope_present__present_enc_impl__enc_stage_impl, &__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i);
    __Vhier.add(&__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i, &__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__0__KET____sbox);
    __Vhier.add(&__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i, &__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__10__KET____sbox);
    __Vhier.add(&__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i, &__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__11__KET____sbox);
    __Vhier.add(&__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i, &__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__12__KET____sbox);
    __Vhier.add(&__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i, &__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__13__KET____sbox);
    __Vhier.add(&__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i, &__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__14__KET____sbox);
    __Vhier.add(&__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i, &__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__15__KET____sbox);
    __Vhier.add(&__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i, &__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__1__KET____sbox);
    __Vhier.add(&__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i, &__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__2__KET____sbox);
    __Vhier.add(&__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i, &__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__3__KET____sbox);
    __Vhier.add(&__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i, &__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__4__KET____sbox);
    __Vhier.add(&__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i, &__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__5__KET____sbox);
    __Vhier.add(&__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i, &__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__6__KET____sbox);
    __Vhier.add(&__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i, &__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__7__KET____sbox);
    __Vhier.add(&__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i, &__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__8__KET____sbox);
    __Vhier.add(&__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i, &__Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__9__KET____sbox);
    
    // Setup export functions
    for (int __Vfinal=0; __Vfinal<2; __Vfinal++) {
        __Vscope_TOP.varInsert(__Vfinal,"block_i", &(TOPp->block_i), VLVT_UINT64,VLVD_IN|VLVF_PUB_RW,1 ,63,0);
        __Vscope_TOP.varInsert(__Vfinal,"block_o", &(TOPp->block_o), VLVT_UINT64,VLVD_OUT|VLVF_PUB_RW,1 ,63,0);
        __Vscope_TOP.varInsert(__Vfinal,"clk", &(TOPp->clk), VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"enc_dec", &(TOPp->enc_dec), VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"end_dec", &(TOPp->end_dec), VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"end_enc", &(TOPp->end_enc), VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"end_key_generation", &(TOPp->end_key_generation), VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"key", &(TOPp->key), VLVT_WDATA,VLVD_IN|VLVF_PUB_RW,1 ,79,0);
        __Vscope_TOP.varInsert(__Vfinal,"rst", &(TOPp->rst), VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_present.varInsert(__Vfinal,"block_i", &(TOPp->present__DOT__block_i), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present.varInsert(__Vfinal,"block_o", &(TOPp->present__DOT__block_o), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present.varInsert(__Vfinal,"block_o_logic", &(TOPp->present__DOT__block_o_logic), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present.varInsert(__Vfinal,"clk", &(TOPp->present__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present.varInsert(__Vfinal,"dec_o", &(TOPp->present__DOT__dec_o), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present.varInsert(__Vfinal,"enc_dec", &(TOPp->present__DOT__enc_dec), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present.varInsert(__Vfinal,"enc_o", &(TOPp->present__DOT__enc_o), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present.varInsert(__Vfinal,"end_dec", &(TOPp->present__DOT__end_dec), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present.varInsert(__Vfinal,"end_enc", &(TOPp->present__DOT__end_enc), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present.varInsert(__Vfinal,"end_key_generation", &(TOPp->present__DOT__end_key_generation), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present.varInsert(__Vfinal,"key", &(TOPp->present__DOT__key), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,79,0);
        __Vscope_present.varInsert(__Vfinal,"key_index", &(TOPp->present__DOT__key_index), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_present.varInsert(__Vfinal,"key_index_dec", &(TOPp->present__DOT__key_index_dec), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_present.varInsert(__Vfinal,"key_index_enc", &(TOPp->present__DOT__key_index_enc), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_present.varInsert(__Vfinal,"roundkey", &(TOPp->present__DOT__roundkey), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present.varInsert(__Vfinal,"rst", &(TOPp->present__DOT__rst), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present.varInsert(__Vfinal,"start_dec", &(TOPp->present__DOT__start_dec), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present.varInsert(__Vfinal,"start_enc", &(TOPp->present__DOT__start_enc), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__key_sch_impl.varInsert(__Vfinal,"clk", &(TOPp->present__DOT__key_sch_impl__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__key_sch_impl.varInsert(__Vfinal,"counter_output", &(TOPp->present__DOT__key_sch_impl__DOT__counter_output), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_present__key_sch_impl.varInsert(__Vfinal,"counter_up", &(TOPp->present__DOT__key_sch_impl__DOT__counter_up), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__key_sch_impl.varInsert(__Vfinal,"current_state", &(TOPp->present__DOT__key_sch_impl__DOT__current_state), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_present__key_sch_impl.varInsert(__Vfinal,"end_signal", &(TOPp->present__DOT__key_sch_impl__DOT__end_signal), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__key_sch_impl.varInsert(__Vfinal,"key", &(TOPp->present__DOT__key_sch_impl__DOT__key), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,79,0);
        __Vscope_present__key_sch_impl.varInsert(__Vfinal,"key_index", &(TOPp->present__DOT__key_sch_impl__DOT__key_index), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_present__key_sch_impl.varInsert(__Vfinal,"key_register_cl", &(TOPp->present__DOT__key_sch_impl__DOT__key_register_cl), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__key_sch_impl.varInsert(__Vfinal,"key_register_input", &(TOPp->present__DOT__key_sch_impl__DOT__key_register_input), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,79,0);
        __Vscope_present__key_sch_impl.varInsert(__Vfinal,"key_register_output", &(TOPp->present__DOT__key_sch_impl__DOT__key_register_output), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,79,0);
        __Vscope_present__key_sch_impl.varInsert(__Vfinal,"key_register_w", &(TOPp->present__DOT__key_sch_impl__DOT__key_register_w), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__key_sch_impl.varInsert(__Vfinal,"mem_addr", &(TOPp->present__DOT__key_sch_impl__DOT__mem_addr), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_present__key_sch_impl.varInsert(__Vfinal,"next_state", &(TOPp->present__DOT__key_sch_impl__DOT__next_state), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_present__key_sch_impl.varInsert(__Vfinal,"r_w", &(TOPp->present__DOT__key_sch_impl__DOT__r_w), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__key_sch_impl.varInsert(__Vfinal,"roundkey", &(TOPp->present__DOT__key_sch_impl__DOT__roundkey), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__key_sch_impl.varInsert(__Vfinal,"rst", &(TOPp->present__DOT__key_sch_impl__DOT__rst), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__key_sch_impl.varInsert(__Vfinal,"s_box_output", &(TOPp->present__DOT__key_sch_impl__DOT__s_box_output), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__key_sch_impl__counter_impl.varInsert(__Vfinal,"clk", &(TOPp->present__DOT__key_sch_impl__DOT__counter_impl__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__key_sch_impl__counter_impl.varInsert(__Vfinal,"din", &(TOPp->present__DOT__key_sch_impl__DOT__counter_impl__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_present__key_sch_impl__counter_impl.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__key_sch_impl__DOT__counter_impl__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_present__key_sch_impl__counter_impl.varInsert(__Vfinal,"down", &(TOPp->present__DOT__key_sch_impl__DOT__counter_impl__DOT__down), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__key_sch_impl__counter_impl.varInsert(__Vfinal,"rst", &(TOPp->present__DOT__key_sch_impl__DOT__counter_impl__DOT__rst), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__key_sch_impl__counter_impl.varInsert(__Vfinal,"up", &(TOPp->present__DOT__key_sch_impl__DOT__counter_impl__DOT__up), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__key_sch_impl__key_register.varInsert(__Vfinal,"cl", &(TOPp->present__DOT__key_sch_impl__DOT__key_register__DOT__cl), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__key_sch_impl__key_register.varInsert(__Vfinal,"clk", &(TOPp->present__DOT__key_sch_impl__DOT__key_register__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__key_sch_impl__key_register.varInsert(__Vfinal,"din", &(TOPp->present__DOT__key_sch_impl__DOT__key_register__DOT__din), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,79,0);
        __Vscope_present__key_sch_impl__key_register.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__key_sch_impl__DOT__key_register__DOT__dout), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,79,0);
        __Vscope_present__key_sch_impl__key_register.varInsert(__Vfinal,"w", &(TOPp->present__DOT__key_sch_impl__DOT__key_register__DOT__w), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__key_sch_impl__memory_impl.varInsert(__Vfinal,"addr", &(TOPp->present__DOT__key_sch_impl__DOT__memory_impl__DOT__addr), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_present__key_sch_impl__memory_impl.varInsert(__Vfinal,"clk", &(TOPp->present__DOT__key_sch_impl__DOT__memory_impl__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__key_sch_impl__memory_impl.varInsert(__Vfinal,"din", &(TOPp->present__DOT__key_sch_impl__DOT__memory_impl__DOT__din), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__key_sch_impl__memory_impl.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__key_sch_impl__DOT__memory_impl__DOT__dout), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__key_sch_impl__memory_impl.varInsert(__Vfinal,"memory_", &(TOPp->present__DOT__key_sch_impl__DOT__memory_impl__DOT__memory_), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,2 ,63,0 ,31,0);
        __Vscope_present__key_sch_impl__memory_impl.varInsert(__Vfinal,"r_w", &(TOPp->present__DOT__key_sch_impl__DOT__memory_impl__DOT__r_w), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__key_sch_impl__sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__key_sch_impl__DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__key_sch_impl__sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__key_sch_impl__DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl.varInsert(__Vfinal,"block_i", &(TOPp->present__DOT__present_dec_impl__DOT__block_i), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_dec_impl.varInsert(__Vfinal,"block_o", &(TOPp->present__DOT__present_dec_impl__DOT__block_o), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_dec_impl.varInsert(__Vfinal,"clk", &(TOPp->present__DOT__present_dec_impl__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_dec_impl.varInsert(__Vfinal,"counter_down", &(TOPp->present__DOT__present_dec_impl__DOT__counter_down), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_dec_impl.varInsert(__Vfinal,"end_signal", &(TOPp->present__DOT__present_dec_impl__DOT__end_signal), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_dec_impl.varInsert(__Vfinal,"key_index", &(TOPp->present__DOT__present_dec_impl__DOT__key_index), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_present__present_dec_impl.varInsert(__Vfinal,"register_output", &(TOPp->present__DOT__present_dec_impl__DOT__register_output), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_dec_impl.varInsert(__Vfinal,"register_w", &(TOPp->present__DOT__present_dec_impl__DOT__register_w), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_dec_impl.varInsert(__Vfinal,"result", &(TOPp->present__DOT__present_dec_impl__DOT__result), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_dec_impl.varInsert(__Vfinal,"roundkey", &(TOPp->present__DOT__present_dec_impl__DOT__roundkey), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_dec_impl.varInsert(__Vfinal,"rst", &(TOPp->present__DOT__present_dec_impl__DOT__rst), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_dec_impl.varInsert(__Vfinal,"start_signal", &(TOPp->present__DOT__present_dec_impl__DOT__start_signal), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_dec_impl.varInsert(__Vfinal,"text", &(TOPp->present__DOT__present_dec_impl__DOT__text), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_dec_impl__block_register.varInsert(__Vfinal,"cl", &(TOPp->present__DOT__present_dec_impl__DOT__block_register__DOT__cl), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_dec_impl__block_register.varInsert(__Vfinal,"clk", &(TOPp->present__DOT__present_dec_impl__DOT__block_register__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_dec_impl__block_register.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_dec_impl__DOT__block_register__DOT__din), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_dec_impl__block_register.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_dec_impl__DOT__block_register__DOT__dout), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_dec_impl__block_register.varInsert(__Vfinal,"w", &(TOPp->present__DOT__present_dec_impl__DOT__block_register__DOT__w), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_dec_impl__counter_impl.varInsert(__Vfinal,"clk", &(TOPp->present__DOT__present_dec_impl__DOT__counter_impl__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_dec_impl__counter_impl.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_dec_impl__DOT__counter_impl__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_present__present_dec_impl__counter_impl.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_dec_impl__DOT__counter_impl__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_present__present_dec_impl__counter_impl.varInsert(__Vfinal,"down", &(TOPp->present__DOT__present_dec_impl__DOT__counter_impl__DOT__down), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_dec_impl__counter_impl.varInsert(__Vfinal,"rst", &(TOPp->present__DOT__present_dec_impl__DOT__counter_impl__DOT__rst), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_dec_impl__counter_impl.varInsert(__Vfinal,"up", &(TOPp->present__DOT__present_dec_impl__DOT__counter_impl__DOT__up), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_dec_impl__dec_stage_impl.varInsert(__Vfinal,"block_i", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__block_i), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_dec_impl__dec_stage_impl.varInsert(__Vfinal,"block_o", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__block_o), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_dec_impl__dec_stage_impl.varInsert(__Vfinal,"key_i", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__key_i), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_dec_impl__dec_stage_impl.varInsert(__Vfinal,"p_layer_o", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__p_layer_o), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_dec_impl__dec_stage_impl.varInsert(__Vfinal,"s_box_o", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__s_box_o), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__player_i.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__player_i__DOT__din), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__player_i.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__player_i__DOT__dout), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__din), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__dout), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__0__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__0__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__0__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__0__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__10__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__10__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__10__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__10__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__11__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__11__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__11__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__11__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__12__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__12__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__12__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__12__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__13__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__13__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__13__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__13__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__14__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__14__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__14__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__14__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__15__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__15__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__15__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__15__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__1__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__1__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__1__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__1__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__2__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__2__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__2__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__2__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__3__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__3__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__3__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__3__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__4__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__4__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__4__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__4__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__5__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__5__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__5__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__5__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__6__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__6__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__6__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__6__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__7__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__7__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__7__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__7__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__8__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__8__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__8__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__8__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__9__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__9__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_dec_impl__dec_stage_impl__slayer_i__genblk1__BRA__9__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_dec_impl__DOT__dec_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__9__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl.varInsert(__Vfinal,"block_i", &(TOPp->present__DOT__present_enc_impl__DOT__block_i), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_enc_impl.varInsert(__Vfinal,"block_o", &(TOPp->present__DOT__present_enc_impl__DOT__block_o), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_enc_impl.varInsert(__Vfinal,"clk", &(TOPp->present__DOT__present_enc_impl__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_enc_impl.varInsert(__Vfinal,"counter_up", &(TOPp->present__DOT__present_enc_impl__DOT__counter_up), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_enc_impl.varInsert(__Vfinal,"end_signal", &(TOPp->present__DOT__present_enc_impl__DOT__end_signal), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_enc_impl.varInsert(__Vfinal,"key_index", &(TOPp->present__DOT__present_enc_impl__DOT__key_index), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_present__present_enc_impl.varInsert(__Vfinal,"register_output", &(TOPp->present__DOT__present_enc_impl__DOT__register_output), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_enc_impl.varInsert(__Vfinal,"register_w", &(TOPp->present__DOT__present_enc_impl__DOT__register_w), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_enc_impl.varInsert(__Vfinal,"result", &(TOPp->present__DOT__present_enc_impl__DOT__result), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_enc_impl.varInsert(__Vfinal,"roundkey", &(TOPp->present__DOT__present_enc_impl__DOT__roundkey), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_enc_impl.varInsert(__Vfinal,"rst", &(TOPp->present__DOT__present_enc_impl__DOT__rst), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_enc_impl.varInsert(__Vfinal,"start_signal", &(TOPp->present__DOT__present_enc_impl__DOT__start_signal), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_enc_impl.varInsert(__Vfinal,"text", &(TOPp->present__DOT__present_enc_impl__DOT__text), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_enc_impl__block_register.varInsert(__Vfinal,"cl", &(TOPp->present__DOT__present_enc_impl__DOT__block_register__DOT__cl), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_enc_impl__block_register.varInsert(__Vfinal,"clk", &(TOPp->present__DOT__present_enc_impl__DOT__block_register__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_enc_impl__block_register.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_enc_impl__DOT__block_register__DOT__din), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_enc_impl__block_register.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_enc_impl__DOT__block_register__DOT__dout), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_enc_impl__block_register.varInsert(__Vfinal,"w", &(TOPp->present__DOT__present_enc_impl__DOT__block_register__DOT__w), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_enc_impl__counter_impl.varInsert(__Vfinal,"clk", &(TOPp->present__DOT__present_enc_impl__DOT__counter_impl__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_enc_impl__counter_impl.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_enc_impl__DOT__counter_impl__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_present__present_enc_impl__counter_impl.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_enc_impl__DOT__counter_impl__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_present__present_enc_impl__counter_impl.varInsert(__Vfinal,"down", &(TOPp->present__DOT__present_enc_impl__DOT__counter_impl__DOT__down), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_enc_impl__counter_impl.varInsert(__Vfinal,"rst", &(TOPp->present__DOT__present_enc_impl__DOT__counter_impl__DOT__rst), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_enc_impl__counter_impl.varInsert(__Vfinal,"up", &(TOPp->present__DOT__present_enc_impl__DOT__counter_impl__DOT__up), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__present_enc_impl__enc_stage_impl.varInsert(__Vfinal,"block_i", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__block_i), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_enc_impl__enc_stage_impl.varInsert(__Vfinal,"block_o", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__block_o), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_enc_impl__enc_stage_impl.varInsert(__Vfinal,"key_i", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__key_i), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_enc_impl__enc_stage_impl.varInsert(__Vfinal,"p_layer_o", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__p_layer_o), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_enc_impl__enc_stage_impl.varInsert(__Vfinal,"s_box_o", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__s_box_o), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__player_i.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__player_i__DOT__din), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__player_i.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__player_i__DOT__dout), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__din), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__dout), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__0__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__0__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__0__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__0__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__10__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__10__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__10__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__10__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__11__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__11__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__11__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__11__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__12__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__12__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__12__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__12__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__13__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__13__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__13__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__13__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__14__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__14__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__14__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__14__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__15__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__15__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__15__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__15__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__1__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__1__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__1__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__1__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__2__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__2__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__2__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__2__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__3__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__3__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__3__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__3__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__4__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__4__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__4__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__4__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__5__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__5__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__5__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__5__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__6__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__6__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__6__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__6__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__7__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__7__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__7__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__7__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__8__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__8__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__8__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__8__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__9__KET____sbox.varInsert(__Vfinal,"din", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__9__KET____DOT__sbox__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__present_enc_impl__enc_stage_impl__slayer_i__genblk1__BRA__9__KET____sbox.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__present_enc_impl__DOT__enc_stage_impl__DOT__slayer_i__DOT__genblk1__BRA__9__KET____DOT__sbox__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_present__result.varInsert(__Vfinal,"cl", &(TOPp->present__DOT__result__DOT__cl), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__result.varInsert(__Vfinal,"clk", &(TOPp->present__DOT__result__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_present__result.varInsert(__Vfinal,"din", &(TOPp->present__DOT__result__DOT__din), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__result.varInsert(__Vfinal,"dout", &(TOPp->present__DOT__result__DOT__dout), VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_present__result.varInsert(__Vfinal,"w", &(TOPp->present__DOT__result__DOT__w), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
    }
}
