// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__Syms.h"
#include "Vtop.h"



// FUNCTIONS
Vtop__Syms::Vtop__Syms(Vtop* topp, const char* namep)
    // Setup locals
    : __Vm_namep(namep)
    , __Vm_didInit(false)
    // Setup submodule names
{
    // Pointer to top level
    TOPp = topp;
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOPp->__Vconfigure(this, true);
    // Setup scopes
    __Vscope_TOP.configure(this, name(), "TOP", "TOP", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter.configure(this, name(), "spongent_iter", "spongent_iter", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__lCounter.configure(this, name(), "spongent_iter.lCounter", "lCounter", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl.configure(this, name(), "spongent_iter.permutation_impl", "permutation_impl", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__counter_impl.configure(this, name(), "spongent_iter.permutation_impl.counter_impl", "counter_impl", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__0__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__0__KET__", "genblk2__BRA\000KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__0__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__0__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__10__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__10__KET__", "genblk2__BRA__10__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__10__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__10__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__11__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__11__KET__", "genblk2__BRA__11__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__11__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__11__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__12__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__12__KET__", "genblk2__BRA__12__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__12__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__12__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__13__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__13__KET__", "genblk2__BRA__13__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__13__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__13__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__14__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__14__KET__", "genblk2__BRA__14__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__14__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__14__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__15__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__15__KET__", "genblk2__BRA__15__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__15__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__15__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__16__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__16__KET__", "genblk2__BRA__16__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__16__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__16__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__17__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__17__KET__", "genblk2__BRA__17__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__17__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__17__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__18__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__18__KET__", "genblk2__BRA__18__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__18__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__18__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__19__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__19__KET__", "genblk2__BRA__19__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__19__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__19__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__1__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__1__KET__", "genblk2__BRA__1__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__1__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__1__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__20__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__20__KET__", "genblk2__BRA__20__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__20__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__20__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__21__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__21__KET__", "genblk2__BRA__21__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__21__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__21__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__22__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__22__KET__", "genblk2__BRA__22__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__22__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__22__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__23__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__23__KET__", "genblk2__BRA__23__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__23__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__23__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__24__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__24__KET__", "genblk2__BRA__24__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__24__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__24__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__25__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__25__KET__", "genblk2__BRA__25__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__25__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__25__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__26__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__26__KET__", "genblk2__BRA__26__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__26__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__26__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__27__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__27__KET__", "genblk2__BRA__27__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__27__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__27__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__28__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__28__KET__", "genblk2__BRA__28__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__28__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__28__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__29__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__29__KET__", "genblk2__BRA__29__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__29__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__29__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__2__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__2__KET__", "genblk2__BRA__2__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__2__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__2__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__30__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__30__KET__", "genblk2__BRA__30__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__30__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__30__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__31__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__31__KET__", "genblk2__BRA__31__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__31__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__31__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__32__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__32__KET__", "genblk2__BRA__32__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__32__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__32__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__33__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__33__KET__", "genblk2__BRA__33__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__33__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__33__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__34__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__34__KET__", "genblk2__BRA__34__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__34__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__34__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__35__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__35__KET__", "genblk2__BRA__35__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__35__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__35__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__36__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__36__KET__", "genblk2__BRA__36__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__36__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__36__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__37__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__37__KET__", "genblk2__BRA__37__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__37__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__37__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__38__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__38__KET__", "genblk2__BRA__38__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__38__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__38__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__39__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__39__KET__", "genblk2__BRA__39__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__39__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__39__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__3__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__3__KET__", "genblk2__BRA__3__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__3__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__3__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__40__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__40__KET__", "genblk2__BRA__40__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__40__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__40__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__41__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__41__KET__", "genblk2__BRA__41__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__41__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__41__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__42__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__42__KET__", "genblk2__BRA__42__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__42__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__42__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__43__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__43__KET__", "genblk2__BRA__43__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__43__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__43__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__44__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__44__KET__", "genblk2__BRA__44__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__44__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__44__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__45__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__45__KET__", "genblk2__BRA__45__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__45__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__45__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__46__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__46__KET__", "genblk2__BRA__46__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__46__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__46__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__47__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__47__KET__", "genblk2__BRA__47__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__47__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__47__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__48__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__48__KET__", "genblk2__BRA__48__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__48__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__48__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__49__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__49__KET__", "genblk2__BRA__49__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__49__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__49__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__4__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__4__KET__", "genblk2__BRA__4__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__4__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__4__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__50__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__50__KET__", "genblk2__BRA__50__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__50__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__50__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__51__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__51__KET__", "genblk2__BRA__51__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__51__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__51__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__52__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__52__KET__", "genblk2__BRA__52__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__52__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__52__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__53__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__53__KET__", "genblk2__BRA__53__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__53__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__53__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__54__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__54__KET__", "genblk2__BRA__54__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__54__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__54__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__55__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__55__KET__", "genblk2__BRA__55__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__55__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__55__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__56__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__56__KET__", "genblk2__BRA__56__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__56__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__56__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__57__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__57__KET__", "genblk2__BRA__57__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__57__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__57__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__58__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__58__KET__", "genblk2__BRA__58__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__58__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__58__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__59__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__59__KET__", "genblk2__BRA__59__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__59__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__59__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__5__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__5__KET__", "genblk2__BRA__5__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__5__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__5__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__60__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__60__KET__", "genblk2__BRA__60__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__60__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__60__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__61__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__61__KET__", "genblk2__BRA__61__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__61__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__61__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__62__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__62__KET__", "genblk2__BRA__62__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__62__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__62__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__63__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__63__KET__", "genblk2__BRA__63__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__63__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__63__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__64__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__64__KET__", "genblk2__BRA__64__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__64__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__64__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__65__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__65__KET__", "genblk2__BRA__65__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__65__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__65__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__66__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__66__KET__", "genblk2__BRA__66__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__66__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__66__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__67__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__67__KET__", "genblk2__BRA__67__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__67__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__67__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__6__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__6__KET__", "genblk2__BRA__6__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__6__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__6__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__7__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__7__KET__", "genblk2__BRA__7__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__7__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__7__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__8__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__8__KET__", "genblk2__BRA__8__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__8__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__8__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__9__KET__.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__9__KET__", "genblk2__BRA__9__KET__", VerilatedScope::SCOPE_OTHER);
    __Vscope_spongent_iter__permutation_impl__genblk2__BRA__9__KET____s_box_i.configure(this, name(), "spongent_iter.permutation_impl.genblk2__BRA__9__KET__.s_box_i", "s_box_i", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__permutation_impl__pLayer_impl.configure(this, name(), "spongent_iter.permutation_impl.pLayer_impl", "pLayer_impl", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__squeezing_phase_impl.configure(this, name(), "spongent_iter.squeezing_phase_impl", "squeezing_phase_impl", VerilatedScope::SCOPE_MODULE);
    __Vscope_spongent_iter__squeezing_phase_impl__counter_impl.configure(this, name(), "spongent_iter.squeezing_phase_impl.counter_impl", "counter_impl", VerilatedScope::SCOPE_MODULE);
    
    // Setup scope hierarchy
    __Vhier.add(0, &__Vscope_spongent_iter);
    __Vhier.add(&__Vscope_spongent_iter, &__Vscope_spongent_iter__lCounter);
    __Vhier.add(&__Vscope_spongent_iter, &__Vscope_spongent_iter__permutation_impl);
    __Vhier.add(&__Vscope_spongent_iter, &__Vscope_spongent_iter__squeezing_phase_impl);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__counter_impl);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__0__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__10__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__11__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__12__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__13__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__14__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__15__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__16__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__17__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__18__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__19__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__1__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__20__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__21__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__22__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__23__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__24__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__25__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__26__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__27__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__28__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__29__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__2__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__30__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__31__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__32__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__33__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__34__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__35__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__36__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__37__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__38__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__39__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__3__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__40__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__41__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__42__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__43__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__44__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__45__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__46__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__47__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__48__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__49__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__4__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__50__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__51__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__52__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__53__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__54__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__55__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__56__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__57__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__58__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__59__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__5__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__60__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__61__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__62__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__63__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__64__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__65__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__66__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__67__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__6__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__7__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__8__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__genblk2__BRA__9__KET____s_box_i);
    __Vhier.add(&__Vscope_spongent_iter__permutation_impl, &__Vscope_spongent_iter__permutation_impl__pLayer_impl);
    __Vhier.add(&__Vscope_spongent_iter__squeezing_phase_impl, &__Vscope_spongent_iter__squeezing_phase_impl__counter_impl);
    
    // Setup export functions
    for (int __Vfinal=0; __Vfinal<2; __Vfinal++) {
        __Vscope_TOP.varInsert(__Vfinal,"busy", &(TOPp->busy), VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"clk", &(TOPp->clk), VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"data_input", &(TOPp->data_input), VLVT_UINT16,VLVD_IN|VLVF_PUB_RW,1 ,15,0);
        __Vscope_TOP.varInsert(__Vfinal,"data_ready", &(TOPp->data_ready), VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"digest", &(TOPp->digest), VLVT_WDATA,VLVD_OUT|VLVF_PUB_RW,1 ,255,0);
        __Vscope_TOP.varInsert(__Vfinal,"end_hash", &(TOPp->end_hash), VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"rst", &(TOPp->rst), VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"start_hash", &(TOPp->start_hash), VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"begin_squeezing", &(TOPp->spongent_iter__DOT__begin_squeezing), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"busy", &(TOPp->spongent_iter__DOT__busy), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"clk", &(TOPp->spongent_iter__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"current_state", &(TOPp->spongent_iter__DOT__current_state), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"data_input", &(TOPp->spongent_iter__DOT__data_input), VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"data_ready", &(TOPp->spongent_iter__DOT__data_ready), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"digest", &(TOPp->spongent_iter__DOT__digest), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,255,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"end_hash", &(TOPp->spongent_iter__DOT__end_hash), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"end_permutation", &(TOPp->spongent_iter__DOT__end_permutation), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"end_squeezing", &(TOPp->spongent_iter__DOT__end_squeezing), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"lCounter_state", &(TOPp->spongent_iter__DOT__lCounter_state), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"last_block", &(TOPp->spongent_iter__DOT__last_block), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"last_initial_state_from_absorb", &(TOPp->spongent_iter__DOT__last_initial_state_from_absorb), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,271,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"last_padded_data", &(TOPp->spongent_iter__DOT__last_padded_data), VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"next_state", &(TOPp->spongent_iter__DOT__next_state), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"permutation_initial_state", &(TOPp->spongent_iter__DOT__permutation_initial_state), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,271,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"permutation_initial_state_from_absorb", &(TOPp->spongent_iter__DOT__permutation_initial_state_from_absorb), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,271,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"permutation_initial_state_from_squezzing", &(TOPp->spongent_iter__DOT__permutation_initial_state_from_squezzing), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,271,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"permutation_state", &(TOPp->spongent_iter__DOT__permutation_state), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,271,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"rst", &(TOPp->spongent_iter__DOT__rst), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"rst_lCounter", &(TOPp->spongent_iter__DOT__rst_lCounter), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"rst_permutation", &(TOPp->spongent_iter__DOT__rst_permutation), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"rst_permutation_from_absorb", &(TOPp->spongent_iter__DOT__rst_permutation_from_absorb), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"rst_permutation_from_squezzing", &(TOPp->spongent_iter__DOT__rst_permutation_from_squezzing), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"rst_squezzing", &(TOPp->spongent_iter__DOT__rst_squezzing), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"shift_lCounter", &(TOPp->spongent_iter__DOT__shift_lCounter), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"standart_initial_state_from_absorb", &(TOPp->spongent_iter__DOT__standart_initial_state_from_absorb), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,271,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"start_hash", &(TOPp->spongent_iter__DOT__start_hash), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter.varInsert(__Vfinal,"state", &(TOPp->spongent_iter__DOT__state), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,271,0);
        __Vscope_spongent_iter__lCounter.varInsert(__Vfinal,"bit_xored", &(TOPp->spongent_iter__DOT__lCounter__DOT__bit_xored), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter__lCounter.varInsert(__Vfinal,"clk", &(TOPp->spongent_iter__DOT__lCounter__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter__lCounter.varInsert(__Vfinal,"feedback_coeff", &(TOPp->spongent_iter__DOT__lCounter__DOT__feedback_coeff), VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,8,0);
        __Vscope_spongent_iter__lCounter.varInsert(__Vfinal,"initial_state", &(TOPp->spongent_iter__DOT__lCounter__DOT__initial_state), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_spongent_iter__lCounter.varInsert(__Vfinal,"rst", &(TOPp->spongent_iter__DOT__lCounter__DOT__rst), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter__lCounter.varInsert(__Vfinal,"shift", &(TOPp->spongent_iter__DOT__lCounter__DOT__shift), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter__lCounter.varInsert(__Vfinal,"state", &(TOPp->spongent_iter__DOT__lCounter__DOT__state), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_spongent_iter__lCounter.varInsert(__Vfinal,"state_reg", &(TOPp->spongent_iter__DOT__lCounter__DOT__state_reg), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_spongent_iter__permutation_impl.varInsert(__Vfinal,"clk", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter__permutation_impl.varInsert(__Vfinal,"counter_o", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__counter_o), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_spongent_iter__permutation_impl.varInsert(__Vfinal,"end_permutation", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__end_permutation), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter__permutation_impl.varInsert(__Vfinal,"initial_state", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__initial_state), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,271,0);
        __Vscope_spongent_iter__permutation_impl.varInsert(__Vfinal,"lCounter_state", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__lCounter_state), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_spongent_iter__permutation_impl.varInsert(__Vfinal,"reverse_lCounter", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__reverse_lCounter), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_spongent_iter__permutation_impl.varInsert(__Vfinal,"rst", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__rst), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter__permutation_impl.varInsert(__Vfinal,"rst_lCounter", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__rst_lCounter), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter__permutation_impl.varInsert(__Vfinal,"shift_lCounter", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__shift_lCounter), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter__permutation_impl.varInsert(__Vfinal,"state", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__state), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,271,0);
        __Vscope_spongent_iter__permutation_impl.varInsert(__Vfinal,"state_S_box", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__state_S_box), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,271,0);
        __Vscope_spongent_iter__permutation_impl.varInsert(__Vfinal,"state_reg", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__state_reg), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,271,0);
        __Vscope_spongent_iter__permutation_impl__counter_impl.varInsert(__Vfinal,"clk", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__counter_impl__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter__permutation_impl__counter_impl.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__counter_impl__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_spongent_iter__permutation_impl__counter_impl.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__counter_impl__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_spongent_iter__permutation_impl__counter_impl.varInsert(__Vfinal,"down", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__counter_impl__DOT__down), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter__permutation_impl__counter_impl.varInsert(__Vfinal,"rst", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__counter_impl__DOT__rst), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter__permutation_impl__counter_impl.varInsert(__Vfinal,"up", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__counter_impl__DOT__up), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__0__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__0__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__0__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__0__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__10__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__10__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__10__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__10__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__11__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__11__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__11__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__11__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__12__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__12__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__12__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__12__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__13__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__13__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__13__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__13__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__14__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__14__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__14__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__14__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__15__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__15__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__15__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__15__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__16__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__16__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__16__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__16__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__17__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__17__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__17__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__17__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__18__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__18__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__18__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__18__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__19__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__19__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__19__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__19__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__1__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__1__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__1__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__1__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__20__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__20__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__20__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__20__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__21__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__21__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__21__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__21__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__22__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__22__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__22__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__22__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__23__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__23__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__23__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__23__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__24__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__24__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__24__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__24__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__25__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__25__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__25__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__25__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__26__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__26__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__26__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__26__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__27__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__27__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__27__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__27__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__28__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__28__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__28__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__28__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__29__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__29__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__29__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__29__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__2__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__2__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__2__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__2__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__30__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__30__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__30__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__30__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__31__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__31__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__31__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__31__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__32__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__32__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__32__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__32__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__33__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__33__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__33__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__33__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__34__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__34__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__34__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__34__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__35__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__35__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__35__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__35__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__36__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__36__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__36__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__36__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__37__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__37__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__37__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__37__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__38__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__38__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__38__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__38__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__39__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__39__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__39__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__39__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__3__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__3__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__3__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__3__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__40__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__40__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__40__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__40__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__41__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__41__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__41__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__41__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__42__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__42__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__42__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__42__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__43__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__43__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__43__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__43__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__44__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__44__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__44__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__44__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__45__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__45__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__45__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__45__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__46__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__46__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__46__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__46__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__47__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__47__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__47__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__47__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__48__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__48__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__48__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__48__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__49__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__49__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__49__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__49__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__4__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__4__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__4__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__4__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__50__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__50__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__50__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__50__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__51__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__51__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__51__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__51__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__52__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__52__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__52__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__52__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__53__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__53__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__53__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__53__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__54__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__54__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__54__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__54__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__55__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__55__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__55__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__55__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__56__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__56__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__56__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__56__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__57__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__57__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__57__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__57__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__58__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__58__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__58__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__58__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__59__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__59__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__59__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__59__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__5__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__5__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__5__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__5__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__60__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__60__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__60__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__60__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__61__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__61__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__61__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__61__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__62__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__62__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__62__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__62__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__63__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__63__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__63__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__63__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__64__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__64__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__64__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__64__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__65__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__65__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__65__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__65__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__66__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__66__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__66__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__66__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__67__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__67__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__67__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__67__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__6__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__6__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__6__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__6__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__7__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__7__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__7__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__7__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__8__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__8__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__8__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__8__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__9__KET____s_box_i.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__9__KET____DOT__s_box_i__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__genblk2__BRA__9__KET____s_box_i.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__genblk2__BRA__9__KET____DOT__s_box_i__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_spongent_iter__permutation_impl__pLayer_impl.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__pLayer_impl__DOT__din), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,271,0);
        __Vscope_spongent_iter__permutation_impl__pLayer_impl.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__permutation_impl__DOT__pLayer_impl__DOT__dout), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,271,0);
        __Vscope_spongent_iter__squeezing_phase_impl.varInsert(__Vfinal,"clk", &(TOPp->spongent_iter__DOT__squeezing_phase_impl__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter__squeezing_phase_impl.varInsert(__Vfinal,"counter_o", &(TOPp->spongent_iter__DOT__squeezing_phase_impl__DOT__counter_o), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_spongent_iter__squeezing_phase_impl.varInsert(__Vfinal,"counter_up", &(TOPp->spongent_iter__DOT__squeezing_phase_impl__DOT__counter_up), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter__squeezing_phase_impl.varInsert(__Vfinal,"current_state", &(TOPp->spongent_iter__DOT__squeezing_phase_impl__DOT__current_state), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_spongent_iter__squeezing_phase_impl.varInsert(__Vfinal,"end_permutation", &(TOPp->spongent_iter__DOT__squeezing_phase_impl__DOT__end_permutation), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter__squeezing_phase_impl.varInsert(__Vfinal,"end_squeezing", &(TOPp->spongent_iter__DOT__squeezing_phase_impl__DOT__end_squeezing), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter__squeezing_phase_impl.varInsert(__Vfinal,"next_state", &(TOPp->spongent_iter__DOT__squeezing_phase_impl__DOT__next_state), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_spongent_iter__squeezing_phase_impl.varInsert(__Vfinal,"permutation_initial_state", &(TOPp->spongent_iter__DOT__squeezing_phase_impl__DOT__permutation_initial_state), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,271,0);
        __Vscope_spongent_iter__squeezing_phase_impl.varInsert(__Vfinal,"permutation_state", &(TOPp->spongent_iter__DOT__squeezing_phase_impl__DOT__permutation_state), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,271,0);
        __Vscope_spongent_iter__squeezing_phase_impl.varInsert(__Vfinal,"result", &(TOPp->spongent_iter__DOT__squeezing_phase_impl__DOT__result), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,255,0);
        __Vscope_spongent_iter__squeezing_phase_impl.varInsert(__Vfinal,"result_chunk", &(TOPp->spongent_iter__DOT__squeezing_phase_impl__DOT__result_chunk), VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_spongent_iter__squeezing_phase_impl.varInsert(__Vfinal,"rst", &(TOPp->spongent_iter__DOT__squeezing_phase_impl__DOT__rst), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter__squeezing_phase_impl.varInsert(__Vfinal,"rst_permutation", &(TOPp->spongent_iter__DOT__squeezing_phase_impl__DOT__rst_permutation), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter__squeezing_phase_impl.varInsert(__Vfinal,"state", &(TOPp->spongent_iter__DOT__squeezing_phase_impl__DOT__state), VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,271,0);
        __Vscope_spongent_iter__squeezing_phase_impl__counter_impl.varInsert(__Vfinal,"clk", &(TOPp->spongent_iter__DOT__squeezing_phase_impl__DOT__counter_impl__DOT__clk), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter__squeezing_phase_impl__counter_impl.varInsert(__Vfinal,"din", &(TOPp->spongent_iter__DOT__squeezing_phase_impl__DOT__counter_impl__DOT__din), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_spongent_iter__squeezing_phase_impl__counter_impl.varInsert(__Vfinal,"dout", &(TOPp->spongent_iter__DOT__squeezing_phase_impl__DOT__counter_impl__DOT__dout), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_spongent_iter__squeezing_phase_impl__counter_impl.varInsert(__Vfinal,"down", &(TOPp->spongent_iter__DOT__squeezing_phase_impl__DOT__counter_impl__DOT__down), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter__squeezing_phase_impl__counter_impl.varInsert(__Vfinal,"rst", &(TOPp->spongent_iter__DOT__squeezing_phase_impl__DOT__counter_impl__DOT__rst), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_spongent_iter__squeezing_phase_impl__counter_impl.varInsert(__Vfinal,"up", &(TOPp->spongent_iter__DOT__squeezing_phase_impl__DOT__counter_impl__DOT__up), VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
    }
}
